const Sdata = [
 { id : 1,
   imgsrc : "https://wallpapercave.com/dwp1x/wp4056410.jpg",
   title : "A netflix Original Series",
   sname : "DARK",
   link : "https://www.netflix.com/title/80100172",
 },
 { id : 2,
   imgsrc : "https://wallpapercave.com/dwp1x/wp5393502.jpg",
   title : "A netflix Original Series",
   sname : "STRANGER THINGS",
   link : "https://www.netflix.com/title/80057281",
 },
 { id : 3,
  imgsrc :"https://wallpapercave.com/wp/wp6756794.jpg",
  title : "A netflix Original Series",
  sname : "Lucifer",
  link : "https://www.netflix.com/Lucifer",
 },
 { id : 4,
  imgsrc : "https://wallpapercave.com/wp/wp9261753.jpg",
  title : "A netflix Original Series",
  sname : "THE RAIN",
  link : "https://www.netflix.com/in/title/80154610",
 },
 { id : 5,
   imgsrc : "https://wallpapercave.com/dwp1x/wp12099915.jpg",
   title : "A netflix Original Series",
   sname : "BREAKING BAD",
   link : "https://www.netflix.com/in/title/70143836",
 },
 { id : 6,
  imgsrc : "https://wallpapercave.com/dwp1x/wp6126886.jpg",
  title : "A Netflix Original Series",
  sname : "MONEY HEIST",
  link : "https://www.netflix.com/in/title/80192098",
 },
 { id : 7,
   imgsrc : "https://wallpapercave.com/dwp1x/wp4056410.jpg",
   title : "A netflix Original Series",
   sname : "DARK",
   link : "https://www.netflix.com/title/80100172",
 },
 { id : 8,
   imgsrc : "https://wallpapercave.com/dwp1x/wp5393502.jpg",
   title : "A netflix Original Series",
   sname : "STRANGER THINGS",
   link : "https://www.netflix.com/title/80057281",
 },
 { id : 9,
  imgsrc : "https://wallpapercave.com/dwp1x/wp7418473.jpg",
  title : "A netflix Original Series",
  sname : "EXTRA CURRICULAR",
  link : "https://www.netflix.com/in/title/80990668",
 },
 { id : 10,
  imgsrc : "https://wallpapercave.com/wp/wp9261753.jpg",
  title : "A netflix Original Series",
  sname : "THE RAIN",
  link : "https://www.netflix.com/in/title/80154610",
 },
 { id : 11,
   imgsrc : "https://wallpapercave.com/dwp1x/wp12099915.jpg",
   title : "A netflix Original Series",
   sname : "BREAKING BAD",
   link : "https://www.netflix.com/in/title/70143836",
 },
 { id : 12,
  imgsrc : "https://wallpapercave.com/dwp1x/wp6126886.jpg",
  title : "A Netflix Original Series",
  sname : "MONEY HEIST",
  link : "https://www.netflix.com/in/title/80192098",
 }
 ];
 export default Sdata;